import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "../config/ThemeRegistry";

export const metadata: Metadata = {
  title: "Comments Section",
  description: "Generated by me bitch",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
